### ISSUE TITLE
Error while scanning directory in case an Exception invalid file frame appear

### ISSUE THREAD

**Issue by ghost** [nrittsti/ntag#1]
**Desktop (please complete the following information):**
- OS and Version: Debian GNU/Linux 11 (bullseye)
- Java Version: openjdk 11.0.13 2021-10-19
- NTag Version: 1.2.12

**Describe the bug**
Error appear while scanning directory 
`ntag.NTagException: Invalid audio frames detected while reading the audiofile.`

**Expected behavior**
Expect just skipping every error file happened.

**To Reproduce**
1. Open NTag
2. Open directory that's contain invalid audio frame file

**Comment by nrittsti** [comment]
thx for reporting this annoying issue
fixed in 1.2.13
