### ISSUE TITLE
Cannot remove org.gnome.Platform/x86_64/45, it is needed by com.github.nrittsti.NTag

### ISSUE THREAD

**Issue by alp-km** [nrittsti/ntag#6]
**Desktop (please complete the following information):**
- OS and Version: Fedora 40 (KDE)
- NTag Version: 1.2.14

**Describe the bug**
When trying OS flatpack update (GNOME Application Platform 45/46/47, KDE Application Platform 6.6) giving error:
`Cannot remove org.gnome.Platform/x86_64/45, it is needed by com.github.nrittsti.NTag`

**Expected behavior**
OS updates without errors.

**To Reproduce**
1. Go to Discover
2. Click on install all updates
3. Some updates are installed, some are not

**Comment by nrittsti** [comment]
Solved with Version 1.2.15 and now using Gnome Runtime 47.
